name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: Viaceslav-Kodesh/Godzilla@master
      with: 
        authUrl: ${{ secrets.OS_AUTH_URL }}
        projectName: ${{ secrets.OS_USERNAME }}
        projectDomainName: ${{ secrets.PROJECT_DOMAIN_NAME }}
        userName: ${{ secrets.OS_USERNAME }}
        DomainName: ${{ secrets.OS_USER_DOMAIN_NAME }}
        userPassword: ${{ secrets.OS_PASSWORD }}
